export interface SearchItem {
  id: string;
  category: "pages" | "articles" | "experian" | "calculator";
  titleEn: string;
  titleEs: string;
  descEn: string;
  descEs: string;
  url: string;
  isExternal?: boolean;
  badgeEn?: string;
  badgeEs?: string;
  keywords: string[];
}

export const SEARCH_INDEX: SearchItem[] = [
  /* ---------- Pages & Tools ---------- */
  {
    id: "chart-your-path",
    category: "calculator",
    titleEn: "Chart Your Path — College Need & Borrowing Calculator",
    titleEs: "Traza tu Camino — Calculadora de Necesidad y Préstamos",
    descEn:
      "Calculate your annual funding gap, total borrowing needed, and federal borrowing cap compliance.",
    descEs:
      "Calcula tu brecha anual de financiamiento, préstamo total necesario y límites federales.",
    url: "/chart-your-path",
    badgeEn: "Calculator",
    badgeEs: "Calculadora",
    keywords: [
      "calculator",
      "gap",
      "funding gap",
      "tuition",
      "cost of attendance",
      "borrowing limit",
      "caps",
      "calculadora",
      "brecha",
      "gastos",
      "matrícula",
      "cuánto pedir",
    ],
  },
  {
    id: "pay-for-school",
    category: "pages",
    titleEn: "Pay for School Hub",
    titleEs: "Centro de Financiamiento para la Escuela",
    descEn:
      "Step-by-step guidance on estimating funding gaps, preparation checklist, and lender options.",
    descEs:
      "Guía paso a paso para estimar tu brecha, lista de preparación y opciones de prestamistas.",
    url: "/pay-for-school",
    badgeEn: "Hub",
    badgeEs: "Centro",
    keywords: [
      "pay for school",
      "finance",
      "tuition",
      "scholarships",
      "lenders",
      "checklist",
      "pagar",
      "financiamiento",
      "becas",
      "prestamistas",
    ],
  },
  {
    id: "educational-resources",
    category: "pages",
    titleEn: "Understand Loans — Educational Resources",
    titleEs: "Entender Préstamos — Recursos Educativos",
    descEn:
      "Explore long-form in-depth analysis from Experian and student-written blog explainers.",
    descEs:
      "Explora análisis detallados de Experian y artículos explicativos escritos por estudiantes.",
    url: "/educational-resources",
    badgeEn: "Hub",
    badgeEs: "Centro",
    keywords: [
      "understand",
      "educational resources",
      "learn",
      "basics",
      "hub",
      "aprender",
      "recursos educativos",
      "entender préstamos",
      "guías",
    ],
  },
  {
    id: "manage-loans",
    category: "pages",
    titleEn: "Manage Loans & Refinancing",
    titleEs: "Gestionar Préstamos y Refinanciación",
    descEn:
      "Track existing graduate loans, explore refinancing tradeoffs, and review repayment terms.",
    descEs:
      "Haz seguimiento de préstamos existentes, explora la refinanciación y revisa opciones de pago.",
    url: "/manage-loans",
    badgeEn: "Deck",
    badgeEs: "Guía",
    keywords: [
      "manage",
      "existing loans",
      "refinance",
      "repayment",
      "servicer",
      "gestionar",
      "préstamos existentes",
      "refinanciar",
      "pagos",
    ],
  },
  {
    id: "in-depth-analysis",
    category: "pages",
    titleEn: "In-Depth Analysis — Experian Resource Library",
    titleEs: "Análisis a Fondo — Biblioteca de Recursos de Experian",
    descEn: "Free downloadable PDF brochures on credit scores and syndicated borrower guides.",
    descEs: "Folletos PDF descargables gratuitos sobre puntajes de crédito y guías sindicalizadas.",
    url: "/in-depth-analysis",
    badgeEn: "Experian",
    badgeEs: "Experian",
    keywords: [
      "in-depth",
      "experian",
      "credit score",
      "brochures",
      "pdf",
      "downloads",
      "análisis a fondo",
      "puntaje de crédito",
      "folletos",
      "descargas",
    ],
  },
  {
    id: "blog",
    category: "pages",
    titleEn: "Grad Navigator Blog — Student Perspectives",
    titleEs: "Blog de Grad Navigator — Perspectivas de Estudiantes",
    descEn:
      "Short, plain-language takes on graduate borrowing, interest formulas, and life after Grad PLUS.",
    descEs: "Artículos breves y directos sobre endeudamiento de posgrado y el fin de Grad PLUS.",
    url: "/blog",
    badgeEn: "Blog",
    badgeEs: "Blog",
    keywords: [
      "blog",
      "articles",
      "student perspectives",
      "posts",
      "stories",
      "artículos",
      "publicaciones",
      "historias de estudiantes",
    ],
  },
  {
    id: "editorial-standards",
    category: "pages",
    titleEn: "Editorial Standards & Disclosure Policy",
    titleEs: "Estándares Editoriales y Política de Divulgación",
    descEn: "Learn how we research, review lenders, maintain editorial integrity, and get paid.",
    descEs:
      "Conoce cómo investigamos, evaluamos prestamistas, mantenemos integridad y nos financiamos.",
    url: "/editorial-standards",
    badgeEn: "Policy",
    badgeEs: "Política",
    keywords: [
      "editorial",
      "standards",
      "disclosure",
      "affiliate",
      "ethics",
      "transparency",
      "estándares editoriales",
      "divulgación",
      "transparencia",
      "política",
    ],
  },

  /* ---------- Student Explainer Articles ---------- */
  {
    id: "article-refinancing",
    category: "articles",
    titleEn: "Refinancing Student Loans, Explained",
    titleEs: "Refinanciación de Préstamos Estudiantiles, Explicada",
    descEn:
      "Understand interest rate cuts vs. permanent loss of federal protections (IDR, PSLF, discharge).",
    descEs:
      "Comprende la reducción de tasas frente a la pérdida permanente de protecciones federales (IDR, PSLF).",
    url: "/blog/refinancing-student-loans",
    badgeEn: "5 min read",
    badgeEs: "5 min lectura",
    keywords: [
      "refinancing",
      "refinance",
      "private loans",
      "interest rate",
      "tradeoff",
      "pslf",
      "idr",
      "consolidation",
      "direct consolidation",
      "fixed vs variable",
      "credit check",
      "refinanciar",
      "refinanciación",
      "tasas privadas",
      "perdida de protecciones",
      "perdida de idr",
    ],
  },
  {
    id: "article-interest-numbers",
    category: "articles",
    titleEn: "Student Loan Interest: by the numbers",
    titleEs: "Intereses de Préstamos Estudiantiles: En Cifras",
    descEn:
      "2026-27 fixed rates (6.52% undergrad, 8.07% grad, 9.07% PLUS), $100k/$200k caps, and real-world costs.",
    descEs:
      "Tasas fijas 2026-27 (6.52% pregrado, 8.07% posgrado, 9.07% PLUS), límites de $100k/$200k y costos reales.",
    url: "/blog/student-loan-interest-by-the-numbers",
    badgeEn: "4 min read",
    badgeEs: "4 min lectura",
    keywords: [
      "interest rates",
      "by the numbers",
      "6.52%",
      "8.07%",
      "9.07%",
      "grad plus ended",
      "100k cap",
      "200k cap",
      "treasury auction",
      "markup",
      "cost calculation",
      "tasas de interés",
      "cifras",
      "limites de endeudamiento",
      "costo de intereses",
    ],
  },
  {
    id: "article-loan-types",
    category: "articles",
    titleEn: "Student Loan Types Cheat Sheet",
    titleEs: "Guía Rápida de Tipos de Préstamos Estudiantiles",
    descEn:
      "Comparison between Direct Subsidized, Unsubsidized, Parent PLUS, Grad PLUS, and Private loans.",
    descEs:
      "Comparación entre préstamos Directos Subsidiados, No Subsidiados, Parent PLUS y Privados.",
    url: "/blog/student-loan-types",
    badgeEn: "3 min read",
    badgeEs: "3 min lectura",
    keywords: [
      "loan types",
      "subsidized",
      "unsubsidized",
      "plus loans",
      "parent plus",
      "private student loans",
      "need based",
      "tipos de préstamos",
      "subsidiados",
      "no subsidiados",
      "préstamos privados",
    ],
  },

  /* ---------- Experian In-Depth & External Resources ---------- */
  {
    id: "exp-how-loans-work",
    category: "experian",
    titleEn: "How Do Student Loans Work? (Experian)",
    titleEs: "¿Cómo Funcionan los Préstamos Estudiantiles? (Experian)",
    descEn:
      "Complete breakdown of principal, interest accrual formulas, grace periods, and loan servicers.",
    descEs:
      "Desglose completo de capital, fórmulas de acumulación de interés, períodos de gracia y administradores.",
    url: "https://www.experian.com/blogs/ask-experian/how-do-student-loans-work/",
    isExternal: true,
    badgeEn: "Experian Guide",
    badgeEs: "Guía Experian",
    keywords: [
      "how loans work",
      "principal",
      "accrual",
      "grace period",
      "daily interest",
      "servicer",
      "cómo funcionan los préstamos",
      "capital",
      "interés diario",
      "período de gracia",
    ],
  },
  {
    id: "exp-repayment",
    category: "experian",
    titleEn: "Student Loan Repayment: Everything You Need to Know (Experian)",
    titleEs: "Pago de Préstamos Estudiantiles: Guía Completa (Experian)",
    descEn:
      "Standard, graduated, and income-driven repayment plans, refinancing, and forgiveness options.",
    descEs:
      "Planes de pago estándar, graduados y basados en ingresos, refinanciación y opciones de perdón.",
    url: "https://www.experian.com/blogs/ask-experian/student-loan-repayment/",
    isExternal: true,
    badgeEn: "Experian Guide",
    badgeEs: "Guía Experian",
    keywords: [
      "repayment",
      "plans",
      "income driven",
      "idr",
      "forgiveness",
      "monthly payment",
      "consolidation",
      "pago de préstamos",
      "planes de pago",
      "perdón de préstamos",
      "estrategias de pago",
    ],
  },
  {
    id: "exp-how-to-get",
    category: "experian",
    titleEn: "How to Get a Student Loan (Experian)",
    titleEs: "Cómo Obtener un Préstamo Estudiantil (Experian)",
    descEn:
      "Step-by-step FAFSA guide, financial aid offers, credit requirements, and private loan applications.",
    descEs:
      "Guía FAFSA paso a paso, ofertas de ayuda financiera, requisitos de crédito y solicitudes privadas.",
    url: "https://www.experian.com/blogs/ask-experian/how-to-get-a-student-loan/",
    isExternal: true,
    badgeEn: "Experian Guide",
    badgeEs: "Guía Experian",
    keywords: [
      "how to get",
      "apply",
      "fafsa",
      "financial aid package",
      "cosigner",
      "credit requirements",
      "cómo obtener",
      "solicitar",
      "ayuda financiera",
      "aval",
      "requisitos",
    ],
  },
  {
    id: "exp-pdf-credit-score-basics",
    category: "experian",
    titleEn: "Credit Score Basics (PDF Brochure)",
    titleEs: "Conceptos Básicos del Puntaje de Crédito (Folleto PDF)",
    descEn:
      "Learn how credit scores are calculated, key factors, and how to build credit during school.",
    descEs:
      "Aprende cómo se calculan los puntajes de crédito y cómo construir crédito durante tus estudios.",
    url: "https://www.experian.com/assets/consumer-education-content/brochures/credit-score-basics.pdf",
    isExternal: true,
    badgeEn: "PDF Download",
    badgeEs: "Descarga PDF",
    keywords: [
      "credit score basics",
      "fico",
      "vantage",
      "credit building",
      "pdf",
      "brochure",
      "puntaje de crédito",
      "conceptos básicos",
      "historial crediticio",
      "folleto pdf",
    ],
  },
  {
    id: "exp-pdf-12-questions",
    category: "experian",
    titleEn: "12 Common Credit Questions (PDF Q&A)",
    titleEs: "12 Preguntas Frecuentes sobre Crédito (PDF)",
    descEn:
      "Direct answers to top questions on credit inquiries, score changes, and credit reports.",
    descEs:
      "Respuestas directas a preguntas frecuentes sobre consultas, variaciones de puntaje e informes.",
    url: "https://www.experian.com/content/dam/marketing/na/assets/corp/consumer-education-content/12-common-credit-questions.pdf",
    isExternal: true,
    badgeEn: "PDF Download",
    badgeEs: "Descarga PDF",
    keywords: [
      "12 questions",
      "hard inquiry",
      "soft inquiry",
      "credit monitoring",
      "pdf",
      "preguntas de crédito",
      "consultas de crédito",
      "monitoreo",
      "folleto",
    ],
  },
  {
    id: "exp-pdf-new-credit",
    category: "experian",
    titleEn: "New Credit Guide (PDF)",
    titleEs: "Guía de Nuevo Crédito (PDF)",
    descEn:
      "Beginner's guide to establishing your first credit line and managing accounts responsibly.",
    descEs:
      "Guía para principiantes sobre cómo establecer tu primera línea de crédito responsablemente.",
    url: "https://www.experian.com/content/dam/marketing/na/assets/corp/consumer-education-content/new-credit.pdf",
    isExternal: true,
    badgeEn: "PDF Download",
    badgeEs: "Descarga PDF",
    keywords: [
      "new credit",
      "first credit card",
      "build credit",
      "establishing credit",
      "pdf",
      "nuevo crédito",
      "primer crédito",
      "construir historial",
      "guía pdf",
    ],
  },
];

export const POPULAR_SEARCHES = [
  { labelEn: "Calculate Funding Gap", labelEs: "Calcular Brecha de Fondos", query: "calculator" },
  {
    labelEn: "Refinancing Tradeoffs",
    labelEs: "Ventajas y Riesgos de Refinanciar",
    query: "refinancing",
  },
  { labelEn: "2026 Interest Rates", labelEs: "Tasas de Interés 2026", query: "interest rates" },
  {
    labelEn: "Subsidized vs Unsubsidized",
    labelEs: "Subsidiados vs No Subsidiados",
    query: "subsidized",
  },
  {
    labelEn: "Experian Credit Guides",
    labelEs: "Guías de Crédito Experian",
    query: "credit score",
  },
];
