/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as ChartYourPathRouteImport } from './routes/chart-your-path'
import { Route as EditorialStandardsRouteImport } from './routes/editorial-standards'
import { Route as EducationalResourcesRouteImport } from './routes/educational-resources'
import { Route as InDepthAnalysisRouteImport } from './routes/in-depth-analysis'
import { Route as LendersRouteImport } from './routes/lenders'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as Loans101RouteImport } from './routes/loans-101'
import { Route as ManageLoansRouteImport } from './routes/manage-loans'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as PayForSchoolRouteImport } from './routes/pay-for-school'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiContactRouteImport } from './routes/api/contact'
import { Route as BlogAiUseInHigherEducationRouteImport } from './routes/blog_.ai-use-in-higher-education'
import { Route as BlogClemsonUniversityTheBestOfBothWorldsRouteImport } from './routes/blog_.clemson-university-the-best-of-both-worlds'
import { Route as BlogMbaPrestigeRoiRouteImport } from './routes/blog_.mba-prestige-roi'
import { Route as BlogPublicVsPrivateGradSchoolRouteImport } from './routes/blog_.public-vs-private-grad-school'
import { Route as BlogRefinancingStudentLoansRouteImport } from './routes/blog_.refinancing-student-loans'
import { Route as BlogStudentLoanInterestByTheNumbersRouteImport } from './routes/blog_.student-loan-interest-by-the-numbers'
import { Route as BlogStudentLoanTypesRouteImport } from './routes/blog_.student-loan-types'
import { Route as BlogStudentLoansPoliticalBackgroundAndFutureRouteImport } from './routes/blog_.student-loans-political-background-and-future'
import { Route as BlogTuitionVsInflationWhichHasGrownMoreRouteImport } from './routes/blog_.tuition-vs-inflation-which-has-grown-more'
import { Route as BlogUniversityOfFloridaTopTierValueRouteImport } from './routes/blog_.university-of-florida-top-tier-value'
import { Route as BlogWhichLawSchoolsAreWorthItRouteImport } from './routes/blog_.which-law-schools-are-worth-it'
import { Route as BlogWhichPhdFieldsAreWorthItRouteImport } from './routes/blog_.which-phd-fields-are-worth-it'
import { Route as FaqSlugRouteImport } from './routes/faq/$slug'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as ApiPublicHooksRegenerateCategorySummaryRouteImport } from './routes/api/public/hooks/regenerate-category-summary'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const ChartYourPathRoute = ChartYourPathRouteImport.update({
  id: '/chart-your-path',
  path: '/chart-your-path',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorialStandardsRoute = EditorialStandardsRouteImport.update({
  id: '/editorial-standards',
  path: '/editorial-standards',
  getParentRoute: () => rootRouteImport,
} as any)
const EducationalResourcesRoute = EducationalResourcesRouteImport.update({
  id: '/educational-resources',
  path: '/educational-resources',
  getParentRoute: () => rootRouteImport,
} as any)
const InDepthAnalysisRoute = InDepthAnalysisRouteImport.update({
  id: '/in-depth-analysis',
  path: '/in-depth-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const LendersRoute = LendersRouteImport.update({
  id: '/lenders',
  path: '/lenders',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const Loans101Route = Loans101RouteImport.update({
  id: '/loans-101',
  path: '/loans-101',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageLoansRoute = ManageLoansRouteImport.update({
  id: '/manage-loans',
  path: '/manage-loans',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const PayForSchoolRoute = PayForSchoolRouteImport.update({
  id: '/pay-for-school',
  path: '/pay-for-school',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContactRoute = ApiContactRouteImport.update({
  id: '/api/contact',
  path: '/api/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogAiUseInHigherEducationRoute =
  BlogAiUseInHigherEducationRouteImport.update({
    id: '/blog_/ai-use-in-higher-education',
    path: '/blog/ai-use-in-higher-education',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogClemsonUniversityTheBestOfBothWorldsRoute =
  BlogClemsonUniversityTheBestOfBothWorldsRouteImport.update({
    id: '/blog_/clemson-university-the-best-of-both-worlds',
    path: '/blog/clemson-university-the-best-of-both-worlds',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogMbaPrestigeRoiRoute = BlogMbaPrestigeRoiRouteImport.update({
  id: '/blog_/mba-prestige-roi',
  path: '/blog/mba-prestige-roi',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogPublicVsPrivateGradSchoolRoute =
  BlogPublicVsPrivateGradSchoolRouteImport.update({
    id: '/blog_/public-vs-private-grad-school',
    path: '/blog/public-vs-private-grad-school',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogRefinancingStudentLoansRoute =
  BlogRefinancingStudentLoansRouteImport.update({
    id: '/blog_/refinancing-student-loans',
    path: '/blog/refinancing-student-loans',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogStudentLoanInterestByTheNumbersRoute =
  BlogStudentLoanInterestByTheNumbersRouteImport.update({
    id: '/blog_/student-loan-interest-by-the-numbers',
    path: '/blog/student-loan-interest-by-the-numbers',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogStudentLoanTypesRoute = BlogStudentLoanTypesRouteImport.update({
  id: '/blog_/student-loan-types',
  path: '/blog/student-loan-types',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogStudentLoansPoliticalBackgroundAndFutureRoute =
  BlogStudentLoansPoliticalBackgroundAndFutureRouteImport.update({
    id: '/blog_/student-loans-political-background-and-future',
    path: '/blog/student-loans-political-background-and-future',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogTuitionVsInflationWhichHasGrownMoreRoute =
  BlogTuitionVsInflationWhichHasGrownMoreRouteImport.update({
    id: '/blog_/tuition-vs-inflation-which-has-grown-more',
    path: '/blog/tuition-vs-inflation-which-has-grown-more',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogUniversityOfFloridaTopTierValueRoute =
  BlogUniversityOfFloridaTopTierValueRouteImport.update({
    id: '/blog_/university-of-florida-top-tier-value',
    path: '/blog/university-of-florida-top-tier-value',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogWhichLawSchoolsAreWorthItRoute =
  BlogWhichLawSchoolsAreWorthItRouteImport.update({
    id: '/blog_/which-law-schools-are-worth-it',
    path: '/blog/which-law-schools-are-worth-it',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogWhichPhdFieldsAreWorthItRoute =
  BlogWhichPhdFieldsAreWorthItRouteImport.update({
    id: '/blog_/which-phd-fields-are-worth-it',
    path: '/blog/which-phd-fields-are-worth-it',
    getParentRoute: () => rootRouteImport,
  } as any)
const FaqSlugRoute = FaqSlugRouteImport.update({
  id: '/faq/$slug',
  path: '/faq/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksRegenerateCategorySummaryRoute =
  ApiPublicHooksRegenerateCategorySummaryRouteImport.update({
    id: '/api/public/hooks/regenerate-category-summary',
    path: '/api/public/hooks/regenerate-category-summary',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apply': typeof ApplyRoute
  '/blog': typeof BlogRoute
  '/chart-your-path': typeof ChartYourPathRoute
  '/editorial-standards': typeof EditorialStandardsRoute
  '/educational-resources': typeof EducationalResourcesRoute
  '/in-depth-analysis': typeof InDepthAnalysisRoute
  '/lenders': typeof LendersRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/loans-101': typeof Loans101Route
  '/manage-loans': typeof ManageLoansRoute
  '/mcp': typeof McpRoute
  '/pay-for-school': typeof PayForSchoolRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/api/chat': typeof ApiChatRoute
  '/api/contact': typeof ApiContactRoute
  '/blog/ai-use-in-higher-education': typeof BlogAiUseInHigherEducationRoute
  '/blog/clemson-university-the-best-of-both-worlds': typeof BlogClemsonUniversityTheBestOfBothWorldsRoute
  '/blog/mba-prestige-roi': typeof BlogMbaPrestigeRoiRoute
  '/blog/public-vs-private-grad-school': typeof BlogPublicVsPrivateGradSchoolRoute
  '/blog/refinancing-student-loans': typeof BlogRefinancingStudentLoansRoute
  '/blog/student-loan-interest-by-the-numbers': typeof BlogStudentLoanInterestByTheNumbersRoute
  '/blog/student-loan-types': typeof BlogStudentLoanTypesRoute
  '/blog/student-loans-political-background-and-future': typeof BlogStudentLoansPoliticalBackgroundAndFutureRoute
  '/blog/tuition-vs-inflation-which-has-grown-more': typeof BlogTuitionVsInflationWhichHasGrownMoreRoute
  '/blog/university-of-florida-top-tier-value': typeof BlogUniversityOfFloridaTopTierValueRoute
  '/blog/which-law-schools-are-worth-it': typeof BlogWhichLawSchoolsAreWorthItRoute
  '/blog/which-phd-fields-are-worth-it': typeof BlogWhichPhdFieldsAreWorthItRoute
  '/faq/$slug': typeof FaqSlugRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/hooks/regenerate-category-summary': typeof ApiPublicHooksRegenerateCategorySummaryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apply': typeof ApplyRoute
  '/blog': typeof BlogRoute
  '/chart-your-path': typeof ChartYourPathRoute
  '/editorial-standards': typeof EditorialStandardsRoute
  '/educational-resources': typeof EducationalResourcesRoute
  '/in-depth-analysis': typeof InDepthAnalysisRoute
  '/lenders': typeof LendersRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/loans-101': typeof Loans101Route
  '/manage-loans': typeof ManageLoansRoute
  '/mcp': typeof McpRoute
  '/pay-for-school': typeof PayForSchoolRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/api/chat': typeof ApiChatRoute
  '/api/contact': typeof ApiContactRoute
  '/blog/ai-use-in-higher-education': typeof BlogAiUseInHigherEducationRoute
  '/blog/clemson-university-the-best-of-both-worlds': typeof BlogClemsonUniversityTheBestOfBothWorldsRoute
  '/blog/mba-prestige-roi': typeof BlogMbaPrestigeRoiRoute
  '/blog/public-vs-private-grad-school': typeof BlogPublicVsPrivateGradSchoolRoute
  '/blog/refinancing-student-loans': typeof BlogRefinancingStudentLoansRoute
  '/blog/student-loan-interest-by-the-numbers': typeof BlogStudentLoanInterestByTheNumbersRoute
  '/blog/student-loan-types': typeof BlogStudentLoanTypesRoute
  '/blog/student-loans-political-background-and-future': typeof BlogStudentLoansPoliticalBackgroundAndFutureRoute
  '/blog/tuition-vs-inflation-which-has-grown-more': typeof BlogTuitionVsInflationWhichHasGrownMoreRoute
  '/blog/university-of-florida-top-tier-value': typeof BlogUniversityOfFloridaTopTierValueRoute
  '/blog/which-law-schools-are-worth-it': typeof BlogWhichLawSchoolsAreWorthItRoute
  '/blog/which-phd-fields-are-worth-it': typeof BlogWhichPhdFieldsAreWorthItRoute
  '/faq/$slug': typeof FaqSlugRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/hooks/regenerate-category-summary': typeof ApiPublicHooksRegenerateCategorySummaryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/apply': typeof ApplyRoute
  '/blog': typeof BlogRoute
  '/chart-your-path': typeof ChartYourPathRoute
  '/editorial-standards': typeof EditorialStandardsRoute
  '/educational-resources': typeof EducationalResourcesRoute
  '/in-depth-analysis': typeof InDepthAnalysisRoute
  '/lenders': typeof LendersRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/loans-101': typeof Loans101Route
  '/manage-loans': typeof ManageLoansRoute
  '/mcp': typeof McpRoute
  '/pay-for-school': typeof PayForSchoolRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/api/chat': typeof ApiChatRoute
  '/api/contact': typeof ApiContactRoute
  '/blog_/ai-use-in-higher-education': typeof BlogAiUseInHigherEducationRoute
  '/blog_/clemson-university-the-best-of-both-worlds': typeof BlogClemsonUniversityTheBestOfBothWorldsRoute
  '/blog_/mba-prestige-roi': typeof BlogMbaPrestigeRoiRoute
  '/blog_/public-vs-private-grad-school': typeof BlogPublicVsPrivateGradSchoolRoute
  '/blog_/refinancing-student-loans': typeof BlogRefinancingStudentLoansRoute
  '/blog_/student-loan-interest-by-the-numbers': typeof BlogStudentLoanInterestByTheNumbersRoute
  '/blog_/student-loan-types': typeof BlogStudentLoanTypesRoute
  '/blog_/student-loans-political-background-and-future': typeof BlogStudentLoansPoliticalBackgroundAndFutureRoute
  '/blog_/tuition-vs-inflation-which-has-grown-more': typeof BlogTuitionVsInflationWhichHasGrownMoreRoute
  '/blog_/university-of-florida-top-tier-value': typeof BlogUniversityOfFloridaTopTierValueRoute
  '/blog_/which-law-schools-are-worth-it': typeof BlogWhichLawSchoolsAreWorthItRoute
  '/blog_/which-phd-fields-are-worth-it': typeof BlogWhichPhdFieldsAreWorthItRoute
  '/faq/$slug': typeof FaqSlugRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/hooks/regenerate-category-summary': typeof ApiPublicHooksRegenerateCategorySummaryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apply'
    | '/blog'
    | '/chart-your-path'
    | '/editorial-standards'
    | '/educational-resources'
    | '/in-depth-analysis'
    | '/lenders'
    | '/llms.txt'
    | '/loans-101'
    | '/manage-loans'
    | '/mcp'
    | '/pay-for-school'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/api/chat'
    | '/api/contact'
    | '/blog/ai-use-in-higher-education'
    | '/blog/clemson-university-the-best-of-both-worlds'
    | '/blog/mba-prestige-roi'
    | '/blog/public-vs-private-grad-school'
    | '/blog/refinancing-student-loans'
    | '/blog/student-loan-interest-by-the-numbers'
    | '/blog/student-loan-types'
    | '/blog/student-loans-political-background-and-future'
    | '/blog/tuition-vs-inflation-which-has-grown-more'
    | '/blog/university-of-florida-top-tier-value'
    | '/blog/which-law-schools-are-worth-it'
    | '/blog/which-phd-fields-are-worth-it'
    | '/faq/$slug'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/hooks/regenerate-category-summary'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/apply'
    | '/blog'
    | '/chart-your-path'
    | '/editorial-standards'
    | '/educational-resources'
    | '/in-depth-analysis'
    | '/lenders'
    | '/llms.txt'
    | '/loans-101'
    | '/manage-loans'
    | '/mcp'
    | '/pay-for-school'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/api/chat'
    | '/api/contact'
    | '/blog/ai-use-in-higher-education'
    | '/blog/clemson-university-the-best-of-both-worlds'
    | '/blog/mba-prestige-roi'
    | '/blog/public-vs-private-grad-school'
    | '/blog/refinancing-student-loans'
    | '/blog/student-loan-interest-by-the-numbers'
    | '/blog/student-loan-types'
    | '/blog/student-loans-political-background-and-future'
    | '/blog/tuition-vs-inflation-which-has-grown-more'
    | '/blog/university-of-florida-top-tier-value'
    | '/blog/which-law-schools-are-worth-it'
    | '/blog/which-phd-fields-are-worth-it'
    | '/faq/$slug'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/hooks/regenerate-category-summary'
  id:
    | '__root__'
    | '/'
    | '/apply'
    | '/blog'
    | '/chart-your-path'
    | '/editorial-standards'
    | '/educational-resources'
    | '/in-depth-analysis'
    | '/lenders'
    | '/llms.txt'
    | '/loans-101'
    | '/manage-loans'
    | '/mcp'
    | '/pay-for-school'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/api/chat'
    | '/api/contact'
    | '/blog_/ai-use-in-higher-education'
    | '/blog_/clemson-university-the-best-of-both-worlds'
    | '/blog_/mba-prestige-roi'
    | '/blog_/public-vs-private-grad-school'
    | '/blog_/refinancing-student-loans'
    | '/blog_/student-loan-interest-by-the-numbers'
    | '/blog_/student-loan-types'
    | '/blog_/student-loans-political-background-and-future'
    | '/blog_/tuition-vs-inflation-which-has-grown-more'
    | '/blog_/university-of-florida-top-tier-value'
    | '/blog_/which-law-schools-are-worth-it'
    | '/blog_/which-phd-fields-are-worth-it'
    | '/faq/$slug'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/hooks/regenerate-category-summary'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApplyRoute: typeof ApplyRoute
  BlogRoute: typeof BlogRoute
  ChartYourPathRoute: typeof ChartYourPathRoute
  EditorialStandardsRoute: typeof EditorialStandardsRoute
  EducationalResourcesRoute: typeof EducationalResourcesRoute
  InDepthAnalysisRoute: typeof InDepthAnalysisRoute
  LendersRoute: typeof LendersRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  Loans101Route: typeof Loans101Route
  ManageLoansRoute: typeof ManageLoansRoute
  McpRoute: typeof McpRoute
  PayForSchoolRoute: typeof PayForSchoolRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiContactRoute: typeof ApiContactRoute
  BlogAiUseInHigherEducationRoute: typeof BlogAiUseInHigherEducationRoute
  BlogClemsonUniversityTheBestOfBothWorldsRoute: typeof BlogClemsonUniversityTheBestOfBothWorldsRoute
  BlogMbaPrestigeRoiRoute: typeof BlogMbaPrestigeRoiRoute
  BlogPublicVsPrivateGradSchoolRoute: typeof BlogPublicVsPrivateGradSchoolRoute
  BlogRefinancingStudentLoansRoute: typeof BlogRefinancingStudentLoansRoute
  BlogStudentLoanInterestByTheNumbersRoute: typeof BlogStudentLoanInterestByTheNumbersRoute
  BlogStudentLoanTypesRoute: typeof BlogStudentLoanTypesRoute
  BlogStudentLoansPoliticalBackgroundAndFutureRoute: typeof BlogStudentLoansPoliticalBackgroundAndFutureRoute
  BlogTuitionVsInflationWhichHasGrownMoreRoute: typeof BlogTuitionVsInflationWhichHasGrownMoreRoute
  BlogUniversityOfFloridaTopTierValueRoute: typeof BlogUniversityOfFloridaTopTierValueRoute
  BlogWhichLawSchoolsAreWorthItRoute: typeof BlogWhichLawSchoolsAreWorthItRoute
  BlogWhichPhdFieldsAreWorthItRoute: typeof BlogWhichPhdFieldsAreWorthItRoute
  FaqSlugRoute: typeof FaqSlugRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicHooksRegenerateCategorySummaryRoute: typeof ApiPublicHooksRegenerateCategorySummaryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chart-your-path': {
      id: '/chart-your-path'
      path: '/chart-your-path'
      fullPath: '/chart-your-path'
      preLoaderRoute: typeof ChartYourPathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editorial-standards': {
      id: '/editorial-standards'
      path: '/editorial-standards'
      fullPath: '/editorial-standards'
      preLoaderRoute: typeof EditorialStandardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/educational-resources': {
      id: '/educational-resources'
      path: '/educational-resources'
      fullPath: '/educational-resources'
      preLoaderRoute: typeof EducationalResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/in-depth-analysis': {
      id: '/in-depth-analysis'
      path: '/in-depth-analysis'
      fullPath: '/in-depth-analysis'
      preLoaderRoute: typeof InDepthAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lenders': {
      id: '/lenders'
      path: '/lenders'
      fullPath: '/lenders'
      preLoaderRoute: typeof LendersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loans-101': {
      id: '/loans-101'
      path: '/loans-101'
      fullPath: '/loans-101'
      preLoaderRoute: typeof Loans101RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage-loans': {
      id: '/manage-loans'
      path: '/manage-loans'
      fullPath: '/manage-loans'
      preLoaderRoute: typeof ManageLoansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay-for-school': {
      id: '/pay-for-school'
      path: '/pay-for-school'
      fullPath: '/pay-for-school'
      preLoaderRoute: typeof PayForSchoolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/contact': {
      id: '/api/contact'
      path: '/api/contact'
      fullPath: '/api/contact'
      preLoaderRoute: typeof ApiContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog_/ai-use-in-higher-education': {
      id: '/blog_/ai-use-in-higher-education'
      path: '/blog/ai-use-in-higher-education'
      fullPath: '/blog/ai-use-in-higher-education'
      preLoaderRoute: typeof BlogAiUseInHigherEducationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog_/clemson-university-the-best-of-both-worlds': {
      id: '/blog_/clemson-university-the-best-of-both-worlds'
      path: '/blog/clemson-university-the-best-of-both-worlds'
      fullPath: '/blog/clemson-university-the-best-of-both-worlds'
      preLoaderRoute: typeof BlogClemsonUniversityTheBestOfBothWorldsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog_/mba-prestige-roi': {
      id: '/blog_/mba-prestige-roi'
      path: '/blog/mba-prestige-roi'
      fullPath: '/blog/mba-prestige-roi'
      preLoaderRoute: typeof BlogMbaPrestigeRoiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog_/public-vs-private-grad-school': {
      id: '/blog_/public-vs-private-grad-school'
      path: '/blog/public-vs-private-grad-school'
      fullPath: '/blog/public-vs-private-grad-school'
      preLoaderRoute: typeof BlogPublicVsPrivateGradSchoolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog_/refinancing-student-loans': {
      id: '/blog_/refinancing-student-loans'
      path: '/blog/refinancing-student-loans'
      fullPath: '/blog/refinancing-student-loans'
      preLoaderRoute: typeof BlogRefinancingStudentLoansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog_/student-loan-interest-by-the-numbers': {
      id: '/blog_/student-loan-interest-by-the-numbers'
      path: '/blog/student-loan-interest-by-the-numbers'
      fullPath: '/blog/student-loan-interest-by-the-numbers'
      preLoaderRoute: typeof BlogStudentLoanInterestByTheNumbersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog_/student-loan-types': {
      id: '/blog_/student-loan-types'
      path: '/blog/student-loan-types'
      fullPath: '/blog/student-loan-types'
      preLoaderRoute: typeof BlogStudentLoanTypesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog_/student-loans-political-background-and-future': {
      id: '/blog_/student-loans-political-background-and-future'
      path: '/blog/student-loans-political-background-and-future'
      fullPath: '/blog/student-loans-political-background-and-future'
      preLoaderRoute: typeof BlogStudentLoansPoliticalBackgroundAndFutureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog_/tuition-vs-inflation-which-has-grown-more': {
      id: '/blog_/tuition-vs-inflation-which-has-grown-more'
      path: '/blog/tuition-vs-inflation-which-has-grown-more'
      fullPath: '/blog/tuition-vs-inflation-which-has-grown-more'
      preLoaderRoute: typeof BlogTuitionVsInflationWhichHasGrownMoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog_/university-of-florida-top-tier-value': {
      id: '/blog_/university-of-florida-top-tier-value'
      path: '/blog/university-of-florida-top-tier-value'
      fullPath: '/blog/university-of-florida-top-tier-value'
      preLoaderRoute: typeof BlogUniversityOfFloridaTopTierValueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog_/which-law-schools-are-worth-it': {
      id: '/blog_/which-law-schools-are-worth-it'
      path: '/blog/which-law-schools-are-worth-it'
      fullPath: '/blog/which-law-schools-are-worth-it'
      preLoaderRoute: typeof BlogWhichLawSchoolsAreWorthItRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog_/which-phd-fields-are-worth-it': {
      id: '/blog_/which-phd-fields-are-worth-it'
      path: '/blog/which-phd-fields-are-worth-it'
      fullPath: '/blog/which-phd-fields-are-worth-it'
      preLoaderRoute: typeof BlogWhichPhdFieldsAreWorthItRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq/$slug': {
      id: '/faq/$slug'
      path: '/faq/$slug'
      fullPath: '/faq/$slug'
      preLoaderRoute: typeof FaqSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/regenerate-category-summary': {
      id: '/api/public/hooks/regenerate-category-summary'
      path: '/api/public/hooks/regenerate-category-summary'
      fullPath: '/api/public/hooks/regenerate-category-summary'
      preLoaderRoute: typeof ApiPublicHooksRegenerateCategorySummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApplyRoute: ApplyRoute,
  BlogRoute: BlogRoute,
  ChartYourPathRoute: ChartYourPathRoute,
  EditorialStandardsRoute: EditorialStandardsRoute,
  EducationalResourcesRoute: EducationalResourcesRoute,
  InDepthAnalysisRoute: InDepthAnalysisRoute,
  LendersRoute: LendersRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  Loans101Route: Loans101Route,
  ManageLoansRoute: ManageLoansRoute,
  McpRoute: McpRoute,
  PayForSchoolRoute: PayForSchoolRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ApiChatRoute: ApiChatRoute,
  ApiContactRoute: ApiContactRoute,
  BlogAiUseInHigherEducationRoute: BlogAiUseInHigherEducationRoute,
  BlogClemsonUniversityTheBestOfBothWorldsRoute:
    BlogClemsonUniversityTheBestOfBothWorldsRoute,
  BlogMbaPrestigeRoiRoute: BlogMbaPrestigeRoiRoute,
  BlogPublicVsPrivateGradSchoolRoute: BlogPublicVsPrivateGradSchoolRoute,
  BlogRefinancingStudentLoansRoute: BlogRefinancingStudentLoansRoute,
  BlogStudentLoanInterestByTheNumbersRoute:
    BlogStudentLoanInterestByTheNumbersRoute,
  BlogStudentLoanTypesRoute: BlogStudentLoanTypesRoute,
  BlogStudentLoansPoliticalBackgroundAndFutureRoute:
    BlogStudentLoansPoliticalBackgroundAndFutureRoute,
  BlogTuitionVsInflationWhichHasGrownMoreRoute:
    BlogTuitionVsInflationWhichHasGrownMoreRoute,
  BlogUniversityOfFloridaTopTierValueRoute:
    BlogUniversityOfFloridaTopTierValueRoute,
  BlogWhichLawSchoolsAreWorthItRoute: BlogWhichLawSchoolsAreWorthItRoute,
  BlogWhichPhdFieldsAreWorthItRoute: BlogWhichPhdFieldsAreWorthItRoute,
  FaqSlugRoute: FaqSlugRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicHooksRegenerateCategorySummaryRoute:
    ApiPublicHooksRegenerateCategorySummaryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
