insert into public.categories (name, slug, position, summary_text, summary_updated_at) values ('Repayment & Life After You Borrow', 'repayment-and-after', 4, 'How you handle your loans after graduation determines their actual total cost and how smoothly they fit into your financial life. This category covers the major paths available once borrowing ends, from choosing the right federal repayment plan to pursuing public service loan forgiveness. You will learn how income-driven options work, what it really takes to pause your payments during hard times, and how to weigh low monthly payments today against the total interest you will pay over time.

Making changes down the road, like refinancing your debt for a lower interest rate, can save you money, but it comes with permanent trade-offs you should understand before you borrow. These guides explain what you give up when you swap federal protections for private refinancing, how to time your choices, and how to avoid easy missteps. Whether you plan to pursue forgiveness through public service or simply want a clear path to becoming debt-free, this section helps you map out life after graduation.', '2026-08-02T00:00:00Z') on conflict (slug) do update set name=excluded.name, position=excluded.position, summary_text=excluded.summary_text, summary_updated_at=excluded.summary_updated_at;
insert into public.articles (title, slug, category_id, content, position) values ('Federal repayment plans, explained', 'federal-repayment-plans', (select id from public.categories where slug='repayment-and-after'), 'Standard, graduated, and income-driven plans trade monthly payment against total interest. Picking by cash flow alone is expensive.', 0) on conflict (slug) do update set title=excluded.title, content=excluded.content, position=excluded.position, category_id=excluded.category_id;
insert into public.articles (title, slug, category_id, content, position) values ('What loan forgiveness actually requires', 'what-forgiveness-requires', (select id from public.categories where slug='repayment-and-after'), 'Public Service Loan Forgiveness needs qualifying employment, qualifying loans, and qualifying payments — all three, tracked from day one.', 1) on conflict (slug) do update set title=excluded.title, content=excluded.content, position=excluded.position, category_id=excluded.category_id;
insert into public.articles (title, slug, category_id, content, position) values ('Deferment vs. forbearance', 'deferment-vs-forbearance', (select id from public.categories where slug='repayment-and-after'), 'Both pause payments. Only some deferments pause interest, which is the difference that shows up in your balance later.', 2) on conflict (slug) do update set title=excluded.title, content=excluded.content, position=excluded.position, category_id=excluded.category_id;
insert into public.articles (title, slug, category_id, content, position) values ('What you give up going federal to private', 'federal-to-private-tradeoffs', (select id from public.categories where slug='repayment-and-after'), 'Refinancing federal loans privately permanently ends income-driven repayment, federal forbearance, and forgiveness eligibility.', 3) on conflict (slug) do update set title=excluded.title, content=excluded.content, position=excluded.position, category_id=excluded.category_id;
insert into public.articles (title, slug, category_id, content, position) values ('Refinancing after graduation', 'refinancing-after-graduation', (select id from public.categories where slug='repayment-and-after'), 'Once you have income and a credit history, refinancing private debt can lower your rate meaningfully. Timing and job stability matter more than the advertised rate.', 4) on conflict (slug) do update set title=excluded.title, content=excluded.content, position=excluded.position, category_id=excluded.category_id;
insert into public.categories (name, slug, position, summary_text, summary_updated_at) values ('Reducing What You Need to Borrow', 'reducing-what-you-borrow', 5, 'Before taking on loans, exploring every avenue to lower the total amount you need to borrow can save you thousands in future interest. This category focuses on practical strategies to reduce your sticker price and daily expenses before accepting a loan offer. You will learn how to secure assistantships, target overlooked fellowships, and leverage benefits like employer tuition assistance. It also guides you through mapping out a realistic budget that accounts for hidden expenses like health insurance, course fees, and local housing.

Trimming your total debt balance before graduation dramatically lowers your monthly payments and interest costs down the road. However, minimizing what you borrow is not just about cutting costs at all expenses. It requires weighing strategic trade-offs, such as whether working part-time will delay your graduation or if borrowing slightly more to finish sooner is ultimately cheaper. These guides help you evaluate those choices clearly, ensuring you borrow only what serves your long-term goals without compromising your education.', '2026-08-02T00:00:00Z') on conflict (slug) do update set name=excluded.name, position=excluded.position, summary_text=excluded.summary_text, summary_updated_at=excluded.summary_updated_at;
insert into public.articles (title, slug, category_id, content, position) values ('Assistantships and tuition waivers', 'assistantships-and-waivers', (select id from public.categories where slug='reducing-what-you-borrow'), 'Teaching and research assistantships often carry a stipend plus partial or full tuition remission, and departments allocate them late.', 0) on conflict (slug) do update set title=excluded.title, content=excluded.content, position=excluded.position, category_id=excluded.category_id;
insert into public.articles (title, slug, category_id, content, position) values ('Scholarships most grad students never apply for', 'overlooked-grad-scholarships', (select id from public.categories where slug='reducing-what-you-borrow'), 'Field-specific fellowships and departmental awards have tiny applicant pools compared with undergraduate scholarships.', 1) on conflict (slug) do update set title=excluded.title, content=excluded.content, position=excluded.position, category_id=excluded.category_id;
insert into public.articles (title, slug, category_id, content, position) values ('Building a real cost-of-attendance budget', 'real-cost-of-attendance-budget', (select id from public.categories where slug='reducing-what-you-borrow'), 'Tuition is the easy number. Housing, fees, insurance, and exam costs are where the borrowing gap actually opens up.', 2) on conflict (slug) do update set title=excluded.title, content=excluded.content, position=excluded.position, category_id=excluded.category_id;
insert into public.articles (title, slug, category_id, content, position) values ('Work-study and part-time income options', 'work-study-and-part-time-income', (select id from public.categories where slug='reducing-what-you-borrow'), 'Campus employment, tuition-benefit jobs, and employer tuition assistance can shrink the amount you borrow without hurting your studies.', 3) on conflict (slug) do update set title=excluded.title, content=excluded.content, position=excluded.position, category_id=excluded.category_id;
insert into public.articles (title, slug, category_id, content, position) values ('When borrowing more now is the smarter move', 'when-borrowing-more-is-smarter', (select id from public.categories where slug='reducing-what-you-borrow'), 'Sometimes a heavier loan that lets you finish faster costs less than stretching a program out over extra years.', 4) on conflict (slug) do update set title=excluded.title, content=excluded.content, position=excluded.position, category_id=excluded.category_id;