insert into public.categories (name, slug, position, summary_text, summary_updated_at) values ('Qualifying & Getting Approved', 'qualifying-and-approval', 2, 'Understanding how lenders evaluate your application is the first step toward securing the funding you need for graduate school. Private lenders look closely at your credit score, financial history, income, and existing debt. Because many graduate students have short credit histories rather than poor credit records, knowing what underwriters actually seek allows you to position yourself effectively. Taking a few proactive steps to build your credit profile several months before applying can significantly lower your interest rates and save you thousands over the life of your loan.

This category also guides you through the practical realities of using a cosigner and navigating initial rejections. You will learn how adding a creditworthy cosigner affects your approval odds and borrowing costs, as well as how to protect that relationship through clear release terms. If an application gets denied, you will find actionable strategies to address the lender’s specific concerns, adjust your request, or pursue alternative options. These guides ensure you approach the application process with clarity, confidence, and a strong backup plan.', '2026-08-02T00:00:00Z') on conflict (slug) do update set name=excluded.name, position=excluded.position, summary_text=excluded.summary_text, summary_updated_at=excluded.summary_updated_at;
insert into public.articles (title, slug, category_id, content, position) values ('What private lenders actually check', 'what-private-lenders-check', (select id from public.categories where slug='qualifying-and-approval'), 'Credit score, length of history, income, and debt-to-income ratio. Most grad students have a thin file rather than a bad one.', 0) on conflict (slug) do update set title=excluded.title, content=excluded.content, position=excluded.position, category_id=excluded.category_id;
insert into public.articles (title, slug, category_id, content, position) values ('Do I need a cosigner?', 'do-i-need-a-cosigner', (select id from public.categories where slug='qualifying-and-approval'), 'A cosigner with established credit often turns a denial into an approval and can cut more than a point off your rate. They are fully liable for the balance.', 1) on conflict (slug) do update set title=excluded.title, content=excluded.content, position=excluded.position, category_id=excluded.category_id;
insert into public.articles (title, slug, category_id, content, position) values ('How cosigner release works', 'how-cosigner-release-works', (select id from public.categories where slug='qualifying-and-approval'), 'Most lenders release a cosigner after 12 to 36 consecutive on-time payments if you can qualify alone. Get the terms in writing before you sign.', 2) on conflict (slug) do update set title=excluded.title, content=excluded.content, position=excluded.position, category_id=excluded.category_id;
insert into public.articles (title, slug, category_id, content, position) values ('Building credit before you apply', 'building-credit-before-you-apply', (select id from public.categories where slug='qualifying-and-approval'), 'Six to twelve months of on-time payments, low utilization, and no new accounts moves your rate more than most people expect.', 3) on conflict (slug) do update set title=excluded.title, content=excluded.content, position=excluded.position, category_id=excluded.category_id;
insert into public.articles (title, slug, category_id, content, position) values ('Denied? What happens next', 'denied-what-happens-next', (select id from public.categories where slug='qualifying-and-approval'), 'A denial is not the end. Adverse action notices tell you why, and a cosigner, a different lender, or a smaller request often changes the answer.', 4) on conflict (slug) do update set title=excluded.title, content=excluded.content, position=excluded.position, category_id=excluded.category_id;
insert into public.categories (name, slug, position, summary_text, summary_updated_at) values ('What Borrowing Actually Costs', 'what-borrowing-costs', 3, 'When you evaluate a student loan, the number printed at the top of the offer sheet rarely tells the whole story. This category walks you through the actual mechanics of loan pricing, from the crucial distinction between interest rates and annual percentage rates to the hidden impact of upfront origination fees. You will learn how lenders use your credit score to place you within their advertised rate ranges, and why a low initial variable rate can become far more expensive over time than a predictable fixed rate.

Understanding these hidden costs matters because borrowing decisions follow you for a decade or longer. Looking only at a monthly payment can trick you into choosing an offer that costs thousands of dollars more over the life of the loan. By learning to calculate total repayment amounts and compare offers on equal terms, you can evaluate private and federal options with clarity. These guides give you the tools to spot hidden charges before you sign, ensuring you choose a loan that fits your long-term financial reality.', '2026-08-02T00:00:00Z') on conflict (slug) do update set name=excluded.name, position=excluded.position, summary_text=excluded.summary_text, summary_updated_at=excluded.summary_updated_at;
insert into public.articles (title, slug, category_id, content, position) values ('Fixed vs. variable rates', 'fixed-vs-variable-rates', (select id from public.categories where slug='what-borrowing-costs'), 'A fixed rate never moves. A variable rate starts lower and rises with an index, which is a real risk over a ten-year payoff.', 0) on conflict (slug) do update set title=excluded.title, content=excluded.content, position=excluded.position, category_id=excluded.category_id;
insert into public.articles (title, slug, category_id, content, position) values ('The fees that don''t show up in the rate', 'fees-not-in-the-rate', (select id from public.categories where slug='what-borrowing-costs'), 'Origination fees, late fees, and returned-payment charges quietly raise the cost of a loan that looked cheap on the rate sheet.', 1) on conflict (slug) do update set title=excluded.title, content=excluded.content, position=excluded.position, category_id=excluded.category_id;
insert into public.articles (title, slug, category_id, content, position) values ('APR vs. interest rate', 'apr-vs-interest-rate', (select id from public.categories where slug='what-borrowing-costs'), 'The interest rate prices the money; the APR folds in fees. Comparing offers on rate alone can pick the more expensive loan.', 2) on conflict (slug) do update set title=excluded.title, content=excluded.content, position=excluded.position, category_id=excluded.category_id;
insert into public.articles (title, slug, category_id, content, position) values ('How your credit score moves your offer', 'credit-score-and-your-offer', (select id from public.categories where slug='what-borrowing-costs'), 'Advertised ranges are wide for a reason. The bottom of the range goes to strong-credit applicants with a cosigner on a short term.', 3) on conflict (slug) do update set title=excluded.title, content=excluded.content, position=excluded.position, category_id=excluded.category_id;
insert into public.articles (title, slug, category_id, content, position) values ('What $50,000 really costs over 10 years', 'what-50000-costs-over-10-years', (select id from public.categories where slug='what-borrowing-costs'), 'Run the total repaid, not the monthly payment. A couple of points of rate is tens of thousands of dollars across a decade.', 4) on conflict (slug) do update set title=excluded.title, content=excluded.content, position=excluded.position, category_id=excluded.category_id;