-- 1. CREATE TABLES FIRST
CREATE TABLE IF NOT EXISTS public.categories (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  name TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  position INT4 DEFAULT 0,
  summary_text TEXT,
  summary_updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.articles (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  title TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  category_id UUID REFERENCES public.categories(id) ON DELETE CASCADE,
  content TEXT,
  position INT4 DEFAULT 0
);

CREATE TABLE IF NOT EXISTS public.contact_messages (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  reason TEXT NOT NULL,
  message TEXT,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- 2. ENABLE ROW LEVEL SECURITY AND PERMISSIONS
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.articles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.contact_messages ENABLE ROW LEVEL SECURITY;

GRANT SELECT ON public.categories TO anon, authenticated;
GRANT SELECT ON public.articles TO anon, authenticated;
GRANT INSERT ON public.contact_messages TO anon, authenticated;
GRANT ALL ON public.contact_messages TO service_role;

DROP POLICY IF EXISTS "Anyone can submit a contact message" ON public.contact_messages;
CREATE POLICY "Anyone can submit a contact message" ON public.contact_messages FOR INSERT TO anon, authenticated WITH CHECK (
  length(name) BETWEEN 1 AND 100
  AND length(email) BETWEEN 3 AND 255
  AND length(reason) BETWEEN 1 AND 100
  AND (message IS NULL OR length(message) <= 2000)
);

-- 3. INSERT SEED DATA (CATEGORIES AND ARTICLES)
insert into public.categories (name, slug, position, summary_text, summary_updated_at) values ('How Grad Loans Actually Work', 'how-grad-loans-work', 0, 'Taking out graduate student loans involves mechanics that operate differently from undergraduate borrowing or standard consumer debt. This category breaks down the practical realities of how graduate funding functions, from the fundamental differences between federal and private loans to the exact mechanics of disbursement. You will learn how your school receives money first, how living-expense refunds reach your bank account, and how different federal loan types compare in interest rates, fees, and credit requirements. Mastering these basic mechanics helps you avoid costly timing surprises and ensures you understand every term on your paperwork before you sign.

Understanding these mechanics is crucial because small procedural details can quietly add thousands of dollars to your total balance over time. We unpack concepts like interest capitalization—where unpaid interest gets added to your principal—so you can see how debt grows while you are in class and take practical steps to limit that balance. Armed with a clear vocabulary for terms like origination fees and loan servicers, you will be able to evaluate your award letters with confidence, manage your term budget realistically, and choose the loan structure that best protects your financial future.', '2026-08-02T00:00:00Z') on conflict (slug) do update set name=excluded.name, position=excluded.position, summary_text=excluded.summary_text, summary_updated_at=excluded.summary_updated_at;

insert into public.articles (title, slug, category_id, content, position) values ('Federal vs. private grad loans: what''s actually different', 'federal-vs-private-grad-loans', (select id from public.categories where slug='how-grad-loans-work'), 'Federal loans come with fixed rates set by Congress and protections like income-driven repayment. Private loans are underwritten on your credit and priced individually, with far fewer safety nets.', 0) on conflict (slug) do update set title=excluded.title, content=excluded.content, position=excluded.position, category_id=excluded.category_id;
insert into public.articles (title, slug, category_id, content, position) values ('How disbursement works', 'how-disbursement-works', (select id from public.categories where slug='how-grad-loans-work'), 'Loan money goes to your school first, covers tuition and fees, and only the leftover is refunded to you. Timing matters because refunds often arrive weeks after the term starts.', 1) on conflict (slug) do update set title=excluded.title, content=excluded.content, position=excluded.position, category_id=excluded.category_id;
insert into public.articles (title, slug, category_id, content, position) values ('Grad PLUS vs. Direct Unsubsidized Loans', 'grad-plus-vs-direct-unsubsidized', (select id from public.categories where slug='how-grad-loans-work'), 'Direct Unsubsidized loans have a fixed annual limit and no credit check. Grad PLUS historically covered the rest of your cost of attendance but carried higher rates, fees, and a credit review.', 2) on conflict (slug) do update set title=excluded.title, content=excluded.content, position=excluded.position, category_id=excluded.category_id;
insert into public.articles (title, slug, category_id, content, position) values ('Interest capitalization', 'interest-capitalization', (select id from public.categories where slug='how-grad-loans-work'), 'Unpaid interest can be added to your principal at certain points, so you start paying interest on interest. Small payments while in school keep the balance from quietly growing.', 3) on conflict (slug) do update set title=excluded.title, content=excluded.content, position=excluded.position, category_id=excluded.category_id;
insert into public.articles (title, slug, category_id, content, position) values ('A first-time borrower''s glossary', 'first-time-borrower-glossary', (select id from public.categories where slug='how-grad-loans-work'), 'Cost of attendance, origination fee, servicer, forbearance, capitalization — the words that show up on every loan document, in plain English.', 4) on conflict (slug) do update set title=excluded.title, content=excluded.content, position=excluded.position, category_id=excluded.category_id;

insert into public.categories (name, slug, position, summary_text, summary_updated_at) values ('What Changed With Grad PLUS', 'what-changed-grad-plus', 1, 'Federal borrowing rules for graduate school have undergone a major shift, replacing uncapped Grad PLUS loans with strict annual and lifetime limits. This category walks you through how the phase-out works, what the new caps look like for your specific program, and why standard graduate degrees and professional programs are treated differently. Understanding these numbers before you enroll is essential, as the limits determine exactly how much federal funding you can rely on each year.

You will also learn how transition rules apply if you are already enrolled or planning your degree timeline soon. The transition window offers temporary relief for some current students, but it eventually expires and shifts you into the new cap structure mid-program. Exploring these guides will help you pinpoint your exact sunset dates, calculate potential funding shortfalls, and build a realistic financing strategy well before your tuition bills arrive.', '2026-08-02T00:00:00Z') on conflict (slug) do update set name=excluded.name, position=excluded.position, summary_text=excluded.summary_text, summary_updated_at=excluded.summary_updated_at;

insert into public.articles (title, slug, category_id, content, position) values ('The Grad PLUS sunset, start to finish', 'grad-plus-sunset', (select id from public.categories where slug='what-changed-grad-plus'), 'Grad PLUS is being phased out for graduate borrowers, replaced by hard annual and lifetime caps. Here is the timeline and what each date means for you.', 0) on conflict (slug) do update set title=excluded.title, content=excluded.content, position=excluded.position, category_id=excluded.category_id;
insert into public.articles (title, slug, category_id, content, position) values ('New annual and lifetime caps, by degree type', 'new-caps-by-degree-type', (select id from public.categories where slug='what-changed-grad-plus'), 'Standard graduate programs cap at $20,500 a year and $100,000 lifetime. Recognized professional degrees sit at $50,000 a year and $200,000 lifetime.', 1) on conflict (slug) do update set title=excluded.title, content=excluded.content, position=excluded.position, category_id=excluded.category_id;
insert into public.articles (title, slug, category_id, content, position) values ('Am I grandfathered?', 'am-i-grandfathered', (select id from public.categories where slug='what-changed-grad-plus'), 'If you already borrowed Grad PLUS for your current program, a transition window may keep the old rules for up to three academic years. It is tied to the program, not to you.', 2) on conflict (slug) do update set title=excluded.title, content=excluded.content, position=excluded.position, category_id=excluded.category_id;
insert into public.articles (title, slug, category_id, content, position) values ('What happens when your grandfather window ends', 'when-grandfather-window-ends', (select id from public.categories where slug='what-changed-grad-plus'), 'Once the window closes you drop into the new caps mid-degree. Knowing the exact date lets you plan the final year instead of scrambling.', 3) on conflict (slug) do update set title=excluded.title, content=excluded.content, position=excluded.position, category_id=excluded.category_id;
insert into public.articles (title, slug, category_id, content, position) values ('How the change hits professional-degree students differently', 'professional-degree-impact', (select id from public.categories where slug='what-changed-grad-plus'), 'Higher caps sound generous until you compare them with medical, dental, or law school costs. The gap is usually larger, not smaller, for professional students.', 4) on conflict (slug) do update set title=excluded.title, content=excluded.content, position=excluded.position, category_id=excluded.category_id;

insert into public.categories (name, slug, position, summary_text, summary_updated_at) values ('Qualifying & Getting Approved', 'qualifying-and-approval', 2, 'Understanding how lenders evaluate your application is the first step toward securing the funding you need for graduate school. Private lenders look closely at your credit score, financial history, income, and existing debt. Because many graduate students have short credit histories rather than poor credit records, knowing what underwriters actually seek allows you to position yourself effectively. Taking a few proactive steps to build your credit profile several months before applying can significantly lower your interest rates and save you thousands over the life of your loan.

This category also guides you through the practical realities of using a cosigner and navigating initial rejections. You will learn how adding a creditworthy cosigner affects your approval odds and borrowing costs, as well as how to protect that relationship through clear release terms. If an application gets denied, you will find actionable strategies to address the lender’s specific concerns, adjust your request, or pursue alternative options. These guides ensure you approach the application process with clarity, confidence, and a strong backup plan.', '2026-08-02T00:00:00Z') on conflict (slug) do update set name=excluded.name, position=excluded.position, summary_text=excluded.summary_text, summary_updated_at=excluded.summary_updated_at;

insert into public.articles (title, slug, category_id, content, position) values ('What private lenders actually check', 'what-private-lenders-check', (select id from public.categories where slug='qualifying-and-approval'), 'Credit score, length of history, income, and debt-to-income ratio. Most grad students have a thin file rather than a bad one.', 0) on conflict (slug) do update set title=excluded.title, content=excluded.content, position=excluded.position, category_id=excluded.category_id;
insert into public.articles (title, slug, category_id, content, position) values ('Do I need a cosigner?', 'do-i-need-a-cosigner', (select id from public.categories where slug='qualifying-and-approval'), 'A cosigner with established credit often turns a denial into an approval and can cut more than a point off your rate. They are fully liable for the balance.', 1) on conflict (slug) do update set title=excluded.title, content=excluded.content, position=excluded.position, category_id=excluded.category_id;
insert into public.articles (title, slug, category_id, content, position) values ('How cosigner release works', 'how-cosigner-release-works', (select id from public.categories where slug='qualifying-and-approval'), 'Most lenders release a cosigner after 12 to 36 consecutive on-time payments if you can qualify alone. Get the terms in writing before you sign.', 2) on conflict (slug) do update set title=excluded.title, content=excluded.content, position=excluded.position, category_id=excluded.category_id;
insert into public.articles (title, slug, category_id, content, position) values ('Building credit before you apply', 'building-credit-before-you-apply', (select id from public.categories where slug='qualifying-and-approval'), 'Six to twelve months of on-time payments, low utilization, and no new accounts moves your rate more than most people expect.', 3) on conflict (slug) do update set title=excluded.title, content=excluded.content, position=excluded.position, category_id=excluded.category_id;
insert into public.articles (title, slug, category_id, content, position) values ('Denied? What happens next', 'denied-what-happens-next', (select id from public.categories where slug='qualifying-and-approval'), 'A denial is not the end. Adverse action notices tell you why, and a cosigner, a different lender, or a smaller request often changes the answer.', 4) on conflict (slug) do update set title=excluded.title, content=excluded.content, position=excluded.position, category_id=excluded.category_id;

insert into public.categories (name, slug, position, summary_text, summary_updated_at) values ('What Borrowing Actually Costs', 'what-borrowing-costs', 3, 'When you evaluate a student loan, the number printed at the top of the offer sheet rarely tells the whole story. This category walks you through the actual mechanics of loan pricing, from the crucial distinction between interest rates and annual percentage rates to the hidden impact of upfront origination fees. You will learn how lenders use your credit score to place you within their advertised rate ranges, and why a low initial variable rate can become far more expensive over time than a predictable fixed rate.

Understanding these hidden costs matters because borrowing decisions follow you for a decade or longer. Looking only at a monthly payment can trick you into choosing an offer that costs thousands of dollars more over the life of the loan. By learning to calculate total repayment amounts and compare offers on equal terms, you can evaluate private and federal options with clarity. These guides give you the tools to spot hidden charges before you sign, ensuring you choose a loan that fits your long-term financial reality.', '2026-08-02T00:00:00Z') on conflict (slug) do update set name=excluded.name, position=excluded.position, summary_text=excluded.summary_text, summary_updated_at=excluded.summary_updated_at;

insert into public.articles (title, slug, category_id, content, position) values ('Fixed vs. variable rates', 'fixed-vs-variable-rates', (select id from public.categories where slug='what-borrowing-costs'), 'A fixed rate never moves. A variable rate starts lower and rises with an index, which is a real risk over a ten-year payoff.', 0) on conflict (slug) do update set title=excluded.title, content=excluded.content, position=excluded.position, category_id=excluded.category_id;
insert into public.articles (title, slug, category_id, content, position) values ('The fees that don''t show up in the rate', 'fees-not-in-the-rate', (select id from public.categories where slug='what-borrowing-costs'), 'Origination fees, late fees, and returned-payment charges quietly raise the cost of a loan that looked cheap on the rate sheet.', 1) on conflict (slug) do update set title=excluded.title, content=excluded.content, position=excluded.position, category_id=excluded.category_id;
insert into public.articles (title, slug, category_id, content, position) values ('APR vs. interest rate', 'apr-vs-interest-rate', (select id from public.categories where slug='what-borrowing-costs'), 'The interest rate prices the money; the APR folds in fees. Comparing offers on rate alone can pick the more expensive loan.', 2) on conflict (slug) do update set title=excluded.title, content=excluded.content, position=excluded.position, category_id=excluded.category_id;
insert into public.articles (title, slug, category_id, content, position) values ('How your credit score moves your offer', 'credit-score-and-your-offer', (select id from public.categories where slug='what-borrowing-costs'), 'Advertised ranges are wide for a reason. The bottom of the range goes to strong-credit applicants with a cosigner on a short term.', 3) on conflict (slug) do update set title=excluded.title, content=excluded.content, position=excluded.position, category_id=excluded.category_id;
insert into public.articles (title, slug, category_id, content, position) values ('What $50,000 really costs over 10 years', 'what-50000-costs-over-10-years', (select id from public.categories where slug='what-borrowing-costs'), 'Run the total repaid, not the monthly payment. A couple of points of rate is tens of thousands of dollars across a decade.', 4) on conflict (slug) do update set title=excluded.title, content=excluded.content, position=excluded.position, category_id=excluded.category_id;

insert into public.categories (name, slug, position, summary_text, summary_updated_at) values ('Repayment & Life After You Borrow', 'repayment-and-after', 4, 'How you handle your loans after graduation determines their actual total cost and how smoothly they fit into your financial life. This category covers the major paths available once borrowing ends, from choosing the right federal repayment plan to pursuing public service loan forgiveness. You will learn how income-driven options work, what it really takes to pause your payments during hard times, and how to weigh low monthly payments today against the total interest you will pay over time.

Making changes down the road, like refinancing your debt for a lower interest rate, can save you money, but it comes with permanent trade-offs you should understand before you borrow. These guides explain what you give up when you swap federal protections for private refinancing, how to time your choices, and how to avoid easy missteps. Whether you plan to pursue forgiveness through public service or simply want a clear path to becoming debt-free, this section helps you map out life after graduation.', '2026-08-02T00:00:00Z') on conflict (slug) do update set name=excluded.name, position=excluded.position, summary_text=excluded.summary_text, summary_updated_at=excluded.summary_updated_at;

insert into public.articles (title, slug, category_id, content, position) values ('Federal repayment plans, explained', 'federal-repayment-plans', (select id from public.categories where slug='repayment-and-after'), 'Standard, graduated, and income-driven plans trade monthly payment against total interest. Picking by cash flow alone is expensive.', 0) on conflict (slug) do update set title=excluded.title, content=excluded.content, position=excluded.position, category_id=excluded.category_id;
insert into public.articles (title, slug, category_id, content, position) values ('What loan forgiveness actually requires', 'what-forgiveness-requires', (select id from public.categories where slug='repayment-and-after'), 'Public Service Loan Forgiveness needs qualifying employment, qualifying loans, and qualifying payments — all three, tracked from day one.', 1) on conflict (slug) do update set title=excluded.title, content=excluded.content, position=excluded.position, category_id=excluded.category_id;
insert into public.articles (title, slug, category_id, content, position) values ('Deferment vs. forbearance', 'deferment-vs-forbearance', (select id from public.categories where slug='repayment-and-after'), 'Both pause payments. Only some deferments pause interest, which is the difference that shows up in your balance later.', 2) on conflict (slug) do update set title=excluded.title, content=excluded.content, position=excluded.position, category_id=excluded.category_id;
insert into public.articles (title, slug, category_id, content, position) values ('What you give up going federal to private', 'federal-to-private-tradeoffs', (select id from public.categories where slug='repayment-and-after'), 'Refinancing federal loans privately permanently ends income-driven repayment, federal forbearance, and forgiveness eligibility.', 3) on conflict (slug) do update set title=excluded.title, content=excluded.content, position=excluded.position, category_id=excluded.category_id;
insert into public.articles (title, slug, category_id, content, position) values ('Refinancing after graduation', 'refinancing-after-graduation', (select id from public.categories where slug='repayment-and-after'), 'Once you have income and a credit history, refinancing private debt can lower your rate meaningfully. Timing and job stability matter more than the advertised rate.', 4) on conflict (slug) do update set title=excluded.title, content=excluded.content, position=excluded.position, category_id=excluded.category_id;

insert into public.categories (name, slug, position, summary_text, summary_updated_at) values ('Reducing What You Need to Borrow', 'reducing-what-you-borrow', 5, 'Before taking on loans, exploring every avenue to lower the total amount you need to borrow can save you thousands in future interest. This category focuses on practical strategies to reduce your sticker price and daily expenses before accepting a loan offer. You will learn how to secure assistantships, target overlooked fellowships, and leverage benefits like employer tuition assistance. It also guides you through mapping out a realistic budget that accounts for hidden expenses like health insurance, course fees, and local housing.

Trimming your total debt balance before graduation dramatically lowers your monthly payments and interest costs down the road. However, minimizing what you borrow is not just about cutting costs at all expenses. It requires weighing strategic trade-offs, such as whether working part-time will delay your graduation or if borrowing slightly more to finish sooner is ultimately cheaper. These guides help you evaluate those choices clearly, ensuring you borrow only what serves your long-term goals without compromising your education.', '2026-08-02T00:00:00Z') on conflict (slug) do update set name=excluded.name, position=excluded.position, summary_text=excluded.summary_text, summary_updated_at=excluded.summary_updated_at;

insert into public.articles (title, slug, category_id, content, position) values ('Assistantships and tuition waivers', 'assistantships-and-waivers', (select id from public.categories where slug='reducing-what-you-borrow'), 'Teaching and research assistantships often carry a stipend plus partial or full tuition remission, and departments allocate them late.', 0) on conflict (slug) do update set title=excluded.title, content=excluded.content, position=excluded.position, category_id=excluded.category_id;
insert into public.articles (title, slug, category_id, content, position) values ('Scholarships most grad students never apply for', 'overlooked-grad-scholarships', (select id from public.categories where slug='reducing-what-you-borrow'), 'Field-specific fellowships and departmental awards have tiny applicant pools compared with undergraduate scholarships.', 1) on conflict (slug) do update set title=excluded.title, content=excluded.content, position=excluded.position, category_id=excluded.category_id;
insert into public.articles (title, slug, category_id, content, position) values ('Building a real cost-of-attendance budget', 'real-cost-of-attendance-budget', (select id from public.categories where slug='reducing-what-you-borrow'), 'Tuition is the easy number. Housing, fees, insurance, and exam costs are where the borrowing gap actually opens up.', 2) on conflict (slug) do update set title=excluded.title, content=excluded.content, position=excluded.position, category_id=excluded.category_id;
insert into public.articles (title, slug, category_id, content, position) values ('Work-study and part-time income options', 'work-study-and-part-time-income', (select id from public.categories where slug='reducing-what-you-borrow'), 'Campus employment, tuition-benefit jobs, and employer tuition assistance can shrink the amount you borrow without hurting your studies.', 3) on conflict (slug) do update set title=excluded.title, content=excluded.content, position=excluded.position, category_id=excluded.category_id;
insert into public.articles (title, slug, category_id, content, position) values ('When borrowing more now is the smarter move', 'when-borrowing-more-is-smarter', (select id from public.categories where slug='reducing-what-you-borrow'), 'Sometimes a heavier loan that lets you finish faster costs less than stretching a program out over extra years.', 4) on conflict (slug) do update set title=excluded.title, content=excluded.content, position=excluded.position, category_id=excluded.category_id;